wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1752067221
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      4: 3.8.20
      5: 0.12.21
      8:
      - 5
actuator_config:
  desc: null
  value:
    actuator_network_dir: null
    future_len: null
    history_len: null
    prediction_len: null
camera_names:
  desc: null
  value:
  - cam_high
  - cam_left_wrist
  - cam_right_wrist
ckpt_dir:
  desc: null
  value: checkpoint/
episode_len:
  desc: null
  value: null
eval_every:
  desc: null
  value: 500
load_pretrain:
  desc: null
  value: false
lr:
  desc: null
  value: 0.0001
num_steps:
  desc: null
  value: 50
onscreen_render:
  desc: null
  value: false
policy_class:
  desc: null
  value: ACT
policy_config:
  desc: null
  value:
    action_dim: 6
    backbone: resnet18
    camera_names:
    - cam_high
    - cam_left_wrist
    - cam_right_wrist
    dec_layers: 7
    dim_feedforward: null
    enc_layers: 4
    hidden_dim: null
    kl_weight: null
    lr: 0.0001
    lr_backbone: 1.0e-05
    nheads: 8
    no_encoder: false
    num_queries: null
    vq: false
    vq_class: null
    vq_dim: null
real_robot:
  desc: null
  value: true
resume_ckpt_path:
  desc: null
  value: null
save_every:
  desc: null
  value: 500
seed:
  desc: null
  value: 8
state_dim:
  desc: null
  value: 6
task_name:
  desc: null
  value: all
temporal_agg:
  desc: null
  value: false
validate_every:
  desc: null
  value: 500
